title: "Your Wiki Title"
description: "A Wikipedia-like site powered by GitHub Pages and Just the Docs"
remote_theme: "just-the-docs/just-the-docs" 
search_enabled: true
aux_links:
  "GitHub Repository": "https://github.com/chrisboyd-lab/wiki-docs"
logo: "/images/logo.png" 
color_scheme: dark
color_scheme_toggle: true
